network:
    version: 2
    renderer: networkd
    ethernets:
        # Cable internet (RUTX12)
        enp1s0:
            dhcp4: yes
        enp2s0:
            addresses:
             - 10.10.20.1/24
            dhcp4: no
        enp3s0:
            addresses:
             - 10.10.30.1/24
            dhcp4: no
        enp4s0:
            addresses:
             - 10.10.40.1/24
            dhcp4: no
        enp5s0:
            addresses:
             - 10.10.50.1/24
            dhcp4: no
        # Radar       
        enp6s0:
            addresses:
             - 10.10.60.1/24
            dhcp4: no
            routes:
             - to: 236.6.7.0/24
               scope: link