services:
 
  lwe450_TGTD:
    image: ghcr.io/mo-rise/porla-nmea:v0.4.1
    network_mode: host
    restart: unless-stopped
    command: [
      "socat UDP4-RECV:8888,reuseaddr STDOUT | timestamp --rfc3339 | to_bus 1"
    ]
 
  to_zenoh:
    image: ghcr.io/rise-maritime/porla-zenoh:v0.4.2
    network_mode: host
    restart: unless-stopped
    command: [
      "from_bus 1 | jsonify '{timestamp} {value}' | shuffle '{payload_pb2js}' 'rise/v0/landkrabba-one/pubsub/raw/nmea0183/rutx12 {payload_pb2js}' | zenoh put --line '{key} {value}' --encoder 'keelson-enclose-from-json'"
    ]

